typography_spectrum: 0.011407281970605254
content_rating:
  adult: true
color:
  saturation: 0.7449249965138733
  brandStrength: 0.7772306906990707
  lightness: 0.3100160793401301
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  rhythmicContrast: 0.9716755005065352
layout_spectrum: 0.9653900279663503
author:
  name: heather e
  email: heather@heathereschuk.com
name: heather eschuk
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: live life now
