typography_spectrum: 0.29200563044287264
content_rating:
  adult: true
color:
  saturation: 0.8065009578131139
  brandStrength: 0.7036529525648803
  lightness: 0.7780177900567651
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  rhythmicContrast: 0.19334997655823827
layout_spectrum: 0.3071603097487241
author:
  name: heather e
  email: heather@heathereschuk.com
name: heather eschuk
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: live life now
