typography_spectrum: 0.6102773156017065
content_rating:
  adult: true
color:
  saturation: 0.12987184850499034
  brandStrength: 0.009380131727084517
  lightness: 0.17793612577952445
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  rhythmicContrast: 0.560952055035159
layout_spectrum: 0.10142481420189142
author:
  name: heather e
  email: heather@heathereschuk.com
name: heather eschuk
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: live life now
