typography_spectrum: 0.6787234
content_rating:
  adult: true
color:
  saturation: 0.612766
  brandStrength: 0.8768713972531259
  lightness: 0.5148936
  brandColors:
    - '#010409'
    - '#00FFFF'
    - '#01354B'
    - '#FFFFFF'
    - '#0377AA'
  rhythmicContrast: 0
layout_spectrum: 1
author:
  name: heather e
  email: heather@heathereschuk.com
name: heather eschuk
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: live life now
